### ISSUE TITLE
Compress the PNGs

### ISSUE THREAD

**Issue by jefflembeck** [filamentgroup/svg-to-png#1]
Once upon a time not long ago, PNGCrush was used in the grunticon project in order to compress pngs that got crazy unruly in size.

Having a flag in svg-to-png that would allow the output to be compressed to a certain specificity would likely make up for the fact that these pngs come out quite big.

Other options for this: find a way to render the png at a smaller size (unlikely)

**Comment by jefflembeck** [comment]
This is in as of 1.0

**Comment by nwtn** [comment]
👍
