### ISSUE TITLE
Error when using phantomjs 2

### ISSUE THREAD

**Issue by stones** [filamentgroup/svg-to-png#15]
Hey guys,
Another package I use requires phantomjs 2, which them breaks this. Is there an easy way to update to 2?

**Comment by therealpecus** [comment]
@stones  see https://github.com/filamentgroup/grunticon/issues/315
I am making a PR right now

**Comment by therealpecus** [comment]
@jefflembeck this can be closed now that you updated to 3.1.0

**Comment by jefflembeck** [comment]
Fixed with https://github.com/filamentgroup/svg-to-png/commit/9814ae9a19501cfa4f8a28daf9de3bc4698d945f
