### ISSUE TITLE
PhantomJS Fail

### ISSUE THREAD

**Issue by chillybin** [filamentgroup/svg-to-png#17]
A couple of issues seem to have cropped up since upgrading to the GM Seed of MacOS Sierra, I spent a couple of hours today looking into it, but the only solution was to remove grunticon from the gruntfile

```
Running "grunticon:build" (grunticon) task
svg-to-png now spawning phantomjs...
(using path: /node_modules/svg-to-png/node_modules/phantomjs/lib/phantom/bin/phantomjs)

Something went wrong with phantomjs...
Fatal error: Command failed: /node_modules/svg-to-png/node_modules/phantomjs/lib/phantom/bin/phantomjs /node_modules/svg-to-png/lib/phantomscript.js

Process finished with exit code 1
```

See [https://github.com/filamentgroup/grunticon/issues/325](325)

**Comment by jefflembeck** [comment]
Woof. I might need to get Sierra up and running so I can test this, but that might be a few days

I'm in the process of making sure grunticon-lib updates to the latest svg-to-png as well, which _might_ fix this.

Thanks for your patience

**Comment by designorant** [comment]
Not sure if this is related but I've had some issues with **svg-to-png** resulting in various errors on OS X 10.11.6 with Node 6.6.0.

[Upgrading `phantom-unit` from 0.1.1 to 1.0.1](https://github.com/designorant/svg-to-png/commit/a3ec9380b5c534269fe4d8d60872ea6ce9a353bc) has fixed the issue.

**Comment by jefflembeck** [comment]
@designorant thank you. this has been fixed in the latest patch.

**Comment by jefflembeck** [comment]
@chillybin also, this issue is now fixed as well 😁
