### ISSUE TITLE
Buffer version?

### ISSUE THREAD

**Issue by jamen** [filamentgroup/svg-to-png#18]
I'm creating a module where I would like to convert some SVG into a PNG, but I'm not really dealing with files/paths.  Would be nice if there was a buffer version for this.

Right now I can just use `os.tmpdir()` to create the files and convert.

**Comment by jefflembeck** [comment]
@jamen we've been meaning to do this for a bit but just haven't gotten around to it (oss maintenance and all ...)

If you would like to propose a PR, I'd love to work through it with you.
