### ISSUE TITLE
Phantom had an error opening...

### ISSUE THREAD

**Issue by mrmartineau** [filamentgroup/svg-to-png#19]
I am having some problems with my Windows build server, see the below error for more info:

```
svg-to-png now spawning phantomjs...
(using path: C:\TeamCity\buildAgent\work\69e87a68592a97c7\code\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe)

Something went wrong with phantomjs...
PHANTOM ERROR: Error: Error: fail: Phantom had an error opening - C:\TeamCity\buildAgent\temp\buildTmp\grunticon-tmp\arrow-east-blue.svg - Does it exist? true
TRACE:
 -> phantomjs://code/phantomscript.js: 42
 -> phantomjs://platform/rsvp.js: 242 (in function trigger)
 -> phantomjs://platform/rsvp.js: 873
Fatal error: Command failed: C:\TeamCity\buildAgent\work\69e87a68592a97c7\code\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe C:\TeamCity\buildAgent\work\69e87a68592a97c7\code\node_modules\svg-to-png\lib\phantomscript.js ["C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-east-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-east-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-east-yellow.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-mini-east-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-mini-east-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-mini-north-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-mini-west-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-mini-west-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-north-blue-dark.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-north-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-north-paleyellow.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-north-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-south-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-south-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-west-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-west-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\arrow-west-yellow.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\barilla-master-logo.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\chat.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\check--cross.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\check--tick.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\cross-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\cross.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\diet-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\eggtimer--white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\eggtimer.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\email-dark.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\email.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\form-select.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\geo-multi.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\geo.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\globe.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\pack.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\phone.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\print.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\prod-attr--durum.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\question-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\question-yellow.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\question.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\range.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\required.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\reviews.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\search-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\search.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\shape--ditalini.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\shape--elbows.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\shape--farfalle.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\shape--filled.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\shape--largeshells.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\shape--p-regi-reginette-napoletane-v.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\shape--penne.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\shape--twirl.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\skill-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-facebook-transparent.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-facebook-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-facebook.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-instagram-transparent.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-instagram-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-instagram.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-pinterest-transparent.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-pinterest-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-pinterest.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-share-transparent.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-share.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-twitter-transparent.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-twitter-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-twitter.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-youtube-transparent.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-youtube-white.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\social-youtube.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\star-empty.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\star-full.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\star-half.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\time-blue.svg","C:\\TeamCity\\buildAgent\\temp\\buildTmp\\grunticon-tmp\\user-yellow.svg"] sitecore\workspace\Barilla\assets\dist\img\icons\png 400px 300px
PHANTOM ERROR: Error: Error: fail: Phantom had an error opening - C:\TeamCity\buildAgent\temp\buildTmp\grunticon-tmp\arrow-east-blue.svg - Does it exist? true
TRACE:
 -> phantomjs://code/phantomscript.js: 42
 -> phantomjs://platform/rsvp.js: 242 (in function trigger)
 -> phantomjs://platform/rsvp.js: 873
```

I have seen issues like [grunticon/#207](https://github.com/filamentgroup/grunticon/issues/207) & [grunticon#325](https://github.com/filamentgroup/grunticon/issues/325) and the suggestions/fixes  do not seem to work for me..

Any help?

**Comment by jefflembeck** [comment]
I'm definitely interested if it's a permissions issue, do you have access to `C:\TeamCity\buildAgent\temp\buildTmp\grunticon-tmp\arrow-east-blue.svg`?

**Comment by mrmartineau** [comment]
I do, it is a build server. I have looked at the permissions but cannot see a problem. What else might it be?

**Comment by Heidiworld** [comment]
I have this exact same issue. The only way I have found so far of fixing it is reverting svg-to-png back to version 2.0.0 here: node_modules\grunt-grunticon\node_modules\grunticon-lib

**Comment by jvalc** [comment]
Same here. It seems since phantomjs was removed from svg-to-png modules stopped to work.

**Comment by mrmartineau** [comment]
@jvalc was phantom removed recently then?

**Comment by jvalc** [comment]
@mrmartineau well, comparing 2.0.0 with 3.1.0 
2.0.0 uses phantomjs 1.9 as a module dependency which is not there in 3.1.0. 
Instead 3.1 tries to use any existing phantomjs installed across your modules/system.

**Comment by mrmartineau** [comment]
@jvalc so should phantom be installed globally then? If so where is the documentation for that?

cc @jefflembeck

**Comment by jvalc** [comment]
@mrmartineau I tried with phantom installed globally + in the PATH with Admin permissions etc. but it didn't work. 

The best workaround I've found as @Heidiworld mentions is rolling back to 2.0.0. 
I've used [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) to find the dependencies and created this file to install the 2.0 version when running npm install. 

Just create a npm-shrinkwrap.json file in your package.json directory and run npm install. It's not the best but it works until we know what's happening with version 3.1.0. I hope it helps.

`{
  "name": "template",
  "description": "Temporary fix for svg-to-png",
  "version": "0.1.0",
  "dependencies": {
    "grunticon-lib": {
      "version": "^1.2.1",
      "from": "grunticon-lib@>=1.2.1 <2.0.0",
      "dependencies": {
        "svg-to-png": {
          "version": "^2.0.0",
          "from": "svg-to-png@>=2.0.0 <3.0.0"
        }
      }
    }
  }
}`

**Comment by jefflembeck** [comment]
Hrm, sorry all that this is happening.

@jvalc and @Heidiworld, are you also using Windows?

And maybe a gross question, but @mrmartineau, have you tried blowing away your `node_modules` folder? The fact that this works with the deprecated phantomjs package and not with the one that replaced it makes me wonder if there are collisions on your system.

**Comment by jvalc** [comment]
@jefflembeck yes, I'm on Windows. I will try later on Linux.

**Comment by mrmartineau** [comment]
@jefflembeck my build server torches the entire directory on each new build, and I have manually removed the`node_modules` directory as well. Still getting the problems... 

I can run the build locally, on my mac, without any issues by the way

**Comment by mrmartineau** [comment]
@jvalc regarding your temp fix, could changing the version of grunticon itself (svg-to-png is being used as a sub-dependency of grunticon atm) fix the issue?

**Comment by Heidiworld** [comment]
Yes windows. I torched the node_modules folder, updated node and everything else I could think of. Nothing worked except rolling svg-png back

**Comment by jefflembeck** [comment]
Ok. This sounds like we're having an issue with windows machines and the
new phantomjs library that svg-to-png is using. I'll do my best to get a
test environment up and running soon and will report back if I can
reproduce the error.

**Comment by mrmartineau** [comment]
@jefflembeck thanks

**Comment by jvalc** [comment]
@mrmartineau if the version of grunticon uses svg-to-png 2.0 it should work. 
My fix is to use the latest version of grunticon with svg-to-png 2.0 rather than 3.1

@jefflembeck thank you!

**Comment by ivnmaksimovic** [comment]
Same here. Works on Linux, but fails on Windows with same error as @mrmartineau posted.
- `grunt-grunticon@2.3.1`
- `grunticon-lib@1.2.1`

If I switch "svg-to-png": "^3.1.0" inside grunticon-lib package.json to "svg-to-png": "^2.0.0" it works without problems. But of course it will fail again once node_modules folder is reinstalled...

**Comment by KB1RMA** [comment]
I just ran into this issue as well on a fresh `npm install` in our project. Using a slight variant of @jvalc's `npm-shrinkwrap` file appears to solve our issue for now.

**Comment by boneyfantaseas** [comment]
Same error here with a fresh `npm i`.
@ivnmaksimovic 's approach is working for me fine now, too. At least a temporary workaround for Windows machines until a fix is released.

**Comment by Newnab** [comment]
Just as a note for anyone else struggling like I did - I had this issue, but changing svg-to-png's version manually in the grunt-grunticon package.json wasn't solving it.

I was able to solve this issue by rolling grunt-grunticon back to 2.2.0 instead. Not sure if it's just me, but figured I'd post in case it helps someone else.

**Comment by mrmartineau** [comment]
thanks @Newnab, I looked into doing something similar but figured it wouldn't work. Will give it a try later.

**Comment by BouncingBit** [comment]
@Newnab and @mrmartineau : I've tested your suggestion and downgraded grunt-grunticon to version 2.2.0 (was 2.2.3) and the problem is gone...

**Comment by jefflembeck** [comment]
Thank you all for your patience. I still haven't gotten a chance to fix this.

**Comment by johnbender** [comment]
@mrmartineau @jvalc 

If you can point the `svg-to-png` dependency at `filamentgroup/svg-to-png#19` and test out that fix I've posted there it would be much appreciated.

**Comment by mrmartineau** [comment]
@johnbender I will give it a go now. I had no idea that you could use issues with commits as npm dependencies. Thanks

**Comment by mrmartineau** [comment]
@johnbender as this is a bug related to grunticon. Do I still use the latest version of grunticon as well?

**Comment by mrmartineau** [comment]
@johnbender 👏  

I can confirm that my build now works, thank you
