### ISSUE TITLE
bump up imagemin to 5.1.0 to support node7.0

### ISSUE THREAD

**Issue by hans-lizihan** [filamentgroup/svg-to-png#20]
`graceful-fs ^ 1` is included in `imagemin ^ 3`and there is a warning that this module will break in node ^ 7

**Comment by andrew-oxenburgh** [comment]
I've created a pull request for this

**Comment by jdreesen** [comment]
Its not needed to upgrade imagemin to 5.1.0. Version 4.0.0 should suffice because it has a dependecy to `vinyl-fs:^2.1.1` which itself has a dependecy to `graceful-fs:^4.0.0` which supports Node >= 7.

I created PR #30 for this.

**Comment by zachleat** [comment]
This will be included on v4.0.0. Thank you!
