### ISSUE TITLE
bumped imagemin to 5.2.2 failing in travis ci

### ISSUE THREAD

**Issue by andrew-oxenburgh** [filamentgroup/svg-to-png#24]
Hi,

I have submitted a pull request to bump imagemin, but its failing in the travis ci run.

It seems to want to run under node 0.1. Is that still necessary?

**Comment by jefflembeck** [comment]
That's a mistake on viewing things for travisci. It's node 0.10 and given
that roughly 1/4 of node users are on node 0.10 + 0.12, I'm a little
reluctant to make that change.

I'll need to think on it, but it'll certainly be a major version bump.

**Comment by andrew-oxenburgh** [comment]
I'm not sure imagemin 5.0.0 is compatible with node 0.1. It's not in their .travis.yml file.

Another way might be to pull out imagemin from svg-to-png. If a client dev needs it, they can just pipe it, which is kind of what happens in svg-to-png anyway.

I'm not sure if you get the install warning, but I couldn't find a way to exclude optionalDependencies from the packaging in sub packages. The --no-optional flag only seems to work on the main package level.

Imagemin pre-5 won't work on node 7.

**Comment by jefflembeck** [comment]
@andrew-oxenburgh so i've been thinking about it and will likely make this change as part of a small rewrite. It'll have to be a major version bump, unfortunately, because it _will_ break things for people that prior versions support.

It might take a bit, so please bear with me :)

**Comment by andrew-oxenburgh** [comment]
Yeah, no worries. It's better to be a bit conservative and considerate. I can use the fork with my changes until then.

It's imagemin which put you in this situation anyway.

Anything you need doing for it, let me know.

:)

**Comment by deemaxx** [comment]
We would welcome the update discussed here as we're using svg-to-png for our project.

**Comment by jdreesen** [comment]
Its not needed to upgrade imagemin to 5.1.0\. Version 4.0.0 should suffice because it has a dependecy to `vinyl-fs:^2.1.1` which itself has a dependecy to `graceful-fs:^4.0.0` which supports Node >= 7.

I created PR https://github.com/filamentgroup/svg-to-png/pull/30 for this.

Also Node 0.10 and 0.12 reached their End-of-Life in October/December 2016 so I'm not sure we need to support them anymore.

**Comment by zachleat** [comment]
Upcoming svg-to-png v4.0 uses `"node": ">=4"` and uses imagemin 6.0.
