### ISSUE TITLE
Failing with 3.1.2 not 3.1.1

### ISSUE THREAD

**Issue by yanofsky** [filamentgroup/svg-to-png#26]
Not sure how to best describe the issue but when I use `v3.1.2` in a gulp task i get this error:

```shell
Something went wrong with phantomjs...
PHANTOM ERROR: Error: Error: fail: Phantom had an error opening - build/svgs/01.svg - Does it exist? true
TRACE:
 -> phantomjs://code/phantomscript.js: 42
 -> phantomjs://platform/rsvp.js: 242 (in function trigger)
 -> phantomjs://platform/rsvp.js: 873
```

(`build/svgs/01.svg` has permissions of 777)

When I use `v3.1.1`, everything works as expected.

If this is something you want to look into, let me know what else I can provide to help.

(For whatever it's worth, I ended up with these issues after upgrading to macOS Sierra and `v2.0.1` stopped working)

**Comment by estellechvl** [comment]
Hello, did you find a way to fix it ? I'm having the same issue.

**Comment by yanofsky** [comment]
I locked my project to 3.1.1 by using `"svg-to-png": "3.1.1"` in my package.json

**Comment by zachleat** [comment]
Hmm I do see some changes in here that might contribute https://github.com/filamentgroup/svg-to-png/compare/v3.1.1...v3.1.2

I added some additional messaging to hopefully help diagnose this in 4.0.0.

Bear with me, I’m taking over this project and educating myself on this code base.

**Comment by zachleat** [comment]
It might also be helpful if you supply the full filesystem path of `build/svgs/01.svg`. Any extra information is helpful here!

**Comment by panstav** [comment]
Same for me on `3.1.2` and `4.0.0`, no additional information displayed aside from validating that the file does exist.

Anything else I can provide to help with this issue?
