### ISSUE TITLE
PNGs not created in output directory with compress option set to true

### ISSUE THREAD

**Issue by montchr** [filamentgroup/svg-to-png#27]
I've run svg-to-png successfully when `compress` is set to `false` or omitted from the options. However, if I set it to `true`, then no PNGs are created in the output directory.

I've taken a look at the source of the module and was able to locate the missing PNGs within the directory specified in the `tempDir` variable.

If I add a `console.log()` call within the [callback passed to `execFile`](https://github.com/filamentgroup/svg-to-png/blob/master/lib/svg-to-png.js#L75) I get no output.

**Comment by zachleat** [comment]
Hmm, we upgraded Imagemin quite a few major versions in 4.0, can you retest after that is released?

**Comment by zachleat** [comment]
v4.0 is out!
