### ISSUE TITLE
Something went wrong with phantomjs... .Electron build. Error on Windows.

### ISSUE THREAD

**Issue by ms4ever7** [filamentgroup/svg-to-png#28]
I am using Atom Electron to build my project and when i am trying to use  [this](https://www.npmjs.com/package/svg-to-png) module i have an error 
 `Something went wrong with phantomjs...`
The problem is that on  MacOS everything is Ok , but on Windows i get this error

**Comment by zachleat** [comment]
> Sorry, unfortunately we don’t have the resources to provide support for integration with third party frameworks and libs—especially issue reports that do not include reduced test cases. If you have a specific easy-to-debug reduced test case, that would certainly help!

I can say that this package may move to use Puppeteer in the future, which would probably solve your problem. Sorry!
