### ISSUE TITLE
Local and global PhantomJS conflicts

### ISSUE THREAD

**Issue by manovotny** [filamentgroup/svg-to-png#9]
This was discovered while developing locally and then using [CircleCI](https://circleci.com) for automation and deployment.

Locally, I ***do not*** have PhantomJS installed globally. This results in `svg-to-png` using the PhantomJS installed in my project's `node_modules` folder.

However, when I push to GitHub and CircleCI picks things up, [it already has PhantomJS installed globally](https://circleci.com/docs/environment#browsers). This means Grunticon, and thus `svg-to-png`, will use the globally installed PhantomJS *instead* of the PhantomJS installed in the project's `node_modules` folder.

`svg-to-png` expects a certain version of PhantomeJS to be installed (declared in it's `package.json`), but a completely different and potentially incompatible version of PhantomJS can be installed globally, which can produce unexpected results and even never-ending hangs.

It would be nice if you could specify a path for PhantomJS, or even better yet, make the one downloaded in `node_modules` the default or only one that is used.

**Comment by jefflembeck** [comment]
This seems like an issue with the [phantomjs installer package](https://github.com/Medium/phantomjs), as that's what we use to [reference phantomjs](https://github.com/filamentgroup/svg-to-png/blob/master/lib/svg-to-png.js#L22). 

It would be really great if we could figure out a nice, reproducible situation where things are actually breaking. As of right now, I'd expect the phantomjs installer to check globally to make sure the same version required of phantom is installed before just going to it.

**Comment by manovotny** [comment]
Tried as I may, consistent reproducibility was never achievable.

This failed for a string of ~3 days on the CI server after opening the issue and then it never failed again in the following 4 months. At this point, I'd be more willing to call it a fluke on the CI server than anything else.

Sorry for the false alarm!
